name: example
version: 0.0.0+1
publish_to: none

environment:
  sdk: ^2.15.0

dependencies:
  flutter:
    sdk: flutter
  tailwind:
    path: ../../tailwind
  tailwind_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
        - asset: assets/fonts/Inter-ExtraLight.otf
        - asset: assets/fonts/Inter-Light.otf
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-SemiBold.otf
        - asset: assets/fonts/Inter-Bold.otf
        - asset: assets/fonts/Inter-ExtraBold.otf
        - asset: assets/fonts/Inter-Black.otf
